### ISSUE TITLE
People want to see Tinbrain!

### ISSUE THREAD

**Issue by dgant** [Fobbah/tinbrain#1]
Hi Fobbah,

I didn't see a better way of contacting you.

On the Student Starcraft AI Tournament Twitch channel -- https://www.twitch.tv/sscait -- some folks were interested in BWSAL and what it can do.

With a variety of bot frameworks to choose from, it'd help if people could watch BWSAL in action. So however Tinbrain is coming along, people would like to see it in action on SSCAIT! It'd help show what BWSAL can do and encourage people to use it.

**Comment by Fobbah** [comment]
Hi Dan,

It's too bad github doesn't have private messaging anymore ;)

I'll start by saying I didn't write BWSAL - that credit goes to lowerlogic - I simply noticed that it had been gathering dust for a long time on google code, even after the google code shutdown, and decided to export the repository to github and update it to support the latest releases of BWAPI and BWTA(2).

Tinbrain is not a particularly strong bot - i had once written an older much stronger bot using BWSAL called "The Machine", but it has sadly been lost to the sands of time. I had intended to go much further with it, but ran into some limitations with BWSAL, particularly it's inability to cancel MacroTasks which cripples an AI's ability to dynamically switch build orders in response to it's opponent's behaviour - upon stumbling upon this, i stopped working on it.

Some years later now, I've returned my focus to this project I've been tidying up this repository a bit and upgrading it to support the latest revision of BWAPI, and adding doxygen documentation to force myself to dig deeper into the library. BWSAL has many strong capabilities, but its components are heavily coupled with its build order planning logic which may be a bit limiting for some. I'm presently trying to untangle this, and perhaps adapt the planning logic to support deletion of MacroTasks. At the same time, i hope to provide a tighter, well documented API to the end user.

In the meantime, i don't expect to be working on Tinbrain much :)
